version: 0.2

# Buildspec for AWS CodeBuild
# ---------------------------
# This buildspec automates:
# 1. Pulling the latest code from GitHub (triggered by webhook or manual build)
# 2. Ensuring the S3 artifact bucket exists (creates it if missing)
# 3. Logging into Amazon ECR
# 4. Creating ECR repository if missing
# 5. Building Docker image and tagging with commit SHA + "latest"
# 6. Pushing Docker image to ECR
# 7. Creating ECS Fargate cluster if missing
# 8. Registering ECS Task Definition
# 9. Creating ECS Service if missing
# 10. Updating ECS Service with new task definition
# 11. Uploading imagedefinitions.json to S3 with commit SHA for traceability
#
# IMPORTANT:
# The following variables must be configured in the CodeBuild project
# Environment Variables section (not here in buildspec):
# - REPO_NAME
# - ECS_CLUSTER
# - ECS_SERVICE
# - ECS_TASK_DEF_FAMILY
# - S3_BUCKET
# - AWS_REGION
# - ECS_SUBNET  # subnet for Fargate service
# - ECS_SG      # security group for Fargate service
#
# This enables reusable pipelines across environments (dev/stage/prod)

phases:
  pre_build:
    commands:
      - echo "Getting AWS Account ID..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo "Ensuring S3 bucket exists..."
      - |
        aws s3api head-bucket --bucket $S3_BUCKET 2>/dev/null || \
        aws s3 mb s3://$S3_BUCKET --region $AWS_REGION

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - echo "Ensuring ECR repository exists..."
      - |
        aws ecr describe-repositories --repository-names $REPO_NAME || \
        aws ecr create-repository --repository-name $REPO_NAME

      - echo "Setting Docker image tag..."
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPO_NAME:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo "Ensuring ECS cluster exists..."
      - |
        if ! aws ecs describe-clusters --clusters $ECS_CLUSTER | grep -q ACTIVE; then
          aws ecs create-cluster --cluster-name $ECS_CLUSTER
        fi

      - echo "Generating ECS Task Definition JSON..."
      - |
        TASK_DEF_JSON=$(printf '{
          "family": "%s",
          "networkMode": "awsvpc",
          "executionRoleArn": "arn:aws:iam::%s:role/ecsTaskExecutionRole",
          "containerDefinitions": [
            {
              "name": "%s",
              "image": "%s",
              "essential": true,
              "portMappings": [{"containerPort": 80,"hostPort": 80}]
            }
          ],
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "256",
          "memory": "512"
        }' "$ECS_TASK_DEF_FAMILY" "$AWS_ACCOUNT_ID" "$REPO_NAME" "$REPOSITORY_URI:$IMAGE_TAG")
      - echo "$TASK_DEF_JSON" > task-def.json

      - TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo "Task Definition ARN: $TASK_DEF_ARN"

      - echo "Creating/updating ECS Service..."
      - |
        if ! aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE --query 'services[?status==`ACTIVE`].serviceName' --output text | grep -q $ECS_SERVICE; then
          aws ecs create-service \
            --cluster $ECS_CLUSTER \
            --service-name $ECS_SERVICE \
            --task-definition $TASK_DEF_ARN \
            --desired-count 1 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$ECS_SUBNET],securityGroups=[$ECS_SG],assignPublicIp=ENABLED}"
        else
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_DEF_ARN
        fi

      - echo "Uploading imagedefinitions.json to S3..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $REPO_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - aws s3 cp imagedefinitions.json s3://$S3_BUCKET/imagedefinitions-$IMAGE_TAG.json

artifacts:
  files:
    - imagedefinitions.json